apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  client-id: {{ (fromJson (.Files.Get "certs/client_secret.json")).web.client_id | quote }}
  client-secret: {{ (fromJson (.Files.Get "certs/client_secret.json")).web.client_secret | quote }}
  cookie-secret: {{ randAlphaNum 32 | b64enc | quote }}
