apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.user }}
  password: {{ .Values.rabbitmq.password }}
