apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.db.user }}
  password: {{ .Values.db.password }}
