apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.groupDb.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.groupDb.user }}
  password: {{ .Values.groupDb.password }}

