apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.mongodb.user }}
  password: {{ .Values.mongodb.password }}
