namespace: default

image:
  registry: cavedbacr.azurecr.io
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecret:
  name: acr-secret

traefik:
  enabled: true
  service:
    type: LoadBalancer  # or ClusterIP if you have another ingress path
  ingressClass:
    enabled: true
    isDefaultClass: false

db:
  name: cave-db
  user: user
  password: password
  database: cavedb
  storage: 1Gi
  replicas: 1

mongodb:
  name: user-db
  user: user
  password: password
  database: cavemap_users
  storage: 1Gi
  replicas: 1

caveService:
  repository: cave-service
  tag: ""
  image: ""
  replicas: 1
  port: 80
  containerPort: 8000

userService:
  repository: user-service
  tag: ""
  image: ""
  replicas: 1
  port: 80
  containerPort: 3002
  nodeEnv: production

groupService:
  repository: group-service
  tag: ""
  image: ""
  replicas: 1
  port: 80
  containerPort: 8000

mediaService:
  repository: media-service
  tag: ""
  image: ""
  replicas: 1
  port: 80
  containerPort: 8000
  containerName: media-files

groupDb:
  name: group-db
  user: group_user
  password: group_password
  database: group_db
  storage: 1Gi
  replicas: 1

rabbitmq:
  name: rabbitmq
  user: admin
  password: admin123
  storage: 1Gi
  replicas: 1

frontend:
  repository: cave-frontend
  tag: ""
  image: ""
  replicas: 1
  port: 80
  apiBaseUrl: ""  # If empty, defaults to https://{ingress.host}

azureStorage:
  accountName: ""
  accountKey: ""

ingress:
  enabled: true
  tls:
    enabled: true
  className: traefik
  host: localhost.me
  tlsSecret: frontend-cert

serviceUrls:
  apiBase: ""
  caveService: ""
  groupService: ""
  userService: ""
  mediaService: ""
  rabbitmq: ""
  oauth2ProxyAuth: ""
