apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  account-name: {{ .Values.azureStorage.accountName | default "devstorageaccount" }}
  account-key: {{ .Values.azureStorage.accountKey | default "devstorageaccountkey" }}
