{{- $registry := .Values.imagePullSecret.registry | default "" -}}
{{- $username := .Values.imagePullSecret.username | default "" -}}
{{- $password := .Values.imagePullSecret.password | default "" -}}
{{- $email := .Values.imagePullSecret.email | default "unused@example.com" -}}
{{- if and $registry $username $password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name | default "acr-secret" }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" $registry $username $password $email (printf "%s:%s" $username $password | b64enc) | b64enc }}
{{- end }}
