apiVersion: v1
kind: Secret
metadata:
  name: service-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  service-token: {{ .Values.serviceToken | default "dev-service-token-123" }}
