version: "3.9"

services:
  group-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-group_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-group_password}
      POSTGRES_DB: ${POSTGRES_DB:-group_db}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - group_pgdata:/var/lib/postgresql/data

  group-service:
    build: .
    depends_on:
      - group-db
    environment:
      DB_URL: "postgresql+asyncpg://${POSTGRES_USER:-group_user}:${POSTGRES_PASSWORD:-group_password}@group-db:5432/${POSTGRES_DB:-group_db}"
    ports:
      - "8001:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app

volumes:
  group_pgdata:

