{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: frontend-cert
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "certs/localhost.me.pem" | b64enc }}
  tls.key: {{ .Files.Get "certs/localhost.me-key.pem" | b64enc }}
{{- end }}
{{- end }}
